name: Count CPP Files

on:
  push:
    paths:
      - '**.cpp'
      - 'README.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Count .cpp files and update README
        run: |
          count=$(find . -type f -name "*.cpp" | wc -l)
          sed -i "s/📄 Total \`.cpp\` files: .*/📄 Total \`.cpp\` files: **$count**/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git commit -am "Update .cpp file count"
          git push
